/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RecutsSettings = IDL.Record({
  'cutPlaneAngle' : IDL.Float64,
  'showReferenceModel' : IDL.Bool,
  'showSectionHelper' : IDL.Bool,
  'cutPlaneOffset' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'recutsSettings' : RecutsSettings,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRecutsProject' : IDL.Func(
      [IDL.Text, IDL.Text, RecutsSettings],
      [IDL.Nat],
      [],
    ),
  'deleteRecutsProject' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecutsProjectById' : IDL.Func([IDL.Nat], [Project], ['query']),
  'getRecutsProjectsByCaller' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateRecutsProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, RecutsSettings],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RecutsSettings = IDL.Record({
    'cutPlaneAngle' : IDL.Float64,
    'showReferenceModel' : IDL.Bool,
    'showSectionHelper' : IDL.Bool,
    'cutPlaneOffset' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'recutsSettings' : RecutsSettings,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRecutsProject' : IDL.Func(
        [IDL.Text, IDL.Text, RecutsSettings],
        [IDL.Nat],
        [],
      ),
    'deleteRecutsProject' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecutsProjectById' : IDL.Func([IDL.Nat], [Project], ['query']),
    'getRecutsProjectsByCaller' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateRecutsProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, RecutsSettings],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };